name: Semantic Release Dry Run

on:
  push:
    branches:
      - chore/setup-semantic-release

jobs:
  semantic-release-dry-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install python-semantic-release

      - name: Run Semantic Release (Dry Mode)
        run: |
          semantic-release -v --noop version
