name: Release

on:
  push:
    branches:
      - chore/setup-semantic-release

jobs:
  release:
    name: Python Semantic Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # required for changelog and versioning

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install python-semantic-release

      - name: Run Semantic Release (Dry Run)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          semantic-release publish --dry-run --debug
