name: Sync main into dev

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'daronprater'  # Optional: avoids forks doing this

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to access all branches

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync main → dev
        run: |
          git checkout dev
          git merge origin/main --no-ff -m "chore(sync): merge main into dev"
          git push origin dev
